language: node_js
sudo: required
dist: trusty
os:
  - linux
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
branches:
  only:
  - master
node_js:
  - 10
install:
  - npm install
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
jobs:
  include:
    - stage: build & linting & test
      script: npm run ready
      before_deploy: npm run build:kitchensink:prod
      deploy:
        provider: pages
        skip_cleanup: true
        local_dir: ./dist/kitchensink
        github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
        on:
          branch: master

